### ISSUE TITLE
File KEPSREC071.wav (B4 on the piano) doesn't sound right

### ISSUE THREAD

**Issue by JasonYuan869** [KaleidonKep99/Steinway-B-211#1]
The WAV sample for B4 (KEPSREC071.wav) has some crackling in the first few seconds. It's more obvious when played at a higher volume. None of the other notes seem to have this issue.

I can hear it when playing the WAV file itself, and also when using sforzando.

**Comment by KaleidonKep99** [comment]
Which one of the presets is affected?

**Comment by JasonYuan869** [comment]
I hear it on both the Pre 1.8 and the new one, but more on the new one. Again, the louder you play, the more audible it is.

**Comment by JasonYuan869** [comment]
I opened up the WAV file in Audacity and the issue is within the file itself, comparing with the C above it.
![image](https://user-images.githubusercontent.com/18143408/51787784-209a8100-2144-11e9-92d1-742b013209ad.png)
(The top waveform is B, the bottom waveform is C)

**Comment by KaleidonKep99** [comment]
Sorry for making you wait so long, I was busy with stuff irl.
It'll be fixed asap.

**Comment by KaleidonKep99** [comment]
So I've been testing the sample on multiple audio editing tools (Audacity, Adobe Audition, Sony SoundForge...) and none of them reported any issue with the sample.
I also can't hear the crackling, so I recommend trying the SoundFont with a different pair of speakers/headphones.

**Comment by KaleidonKep99** [comment]
Closed for inactivity.
