### ISSUE TITLE
Converting to sf2

### ISSUE THREAD

**Issue by pachadotdev** [KaleidonKep99/Steinway-B-211#5]
@KaleidonKep99 Hi! Do you know how can I use this with qsynth? I've tried converting to sf2 but the resulting file (~650MB) hangs the synthetizer. Otherwise, which software do you recommend to play from a MIDI keyboard but using your B-211 sound?

**Comment by KaleidonKep99** [comment]
Steinway B-211 makes use of specific SFZ-only opcodes that are not supported by the SF2 format.
Converting it will cause these opcodes to be ignored and the resulting SoundFont will not sound as it's meant to do, and it might also have some issues on certain synthesizers (E.g. FluidSynth/QSynth).

I recommend using JACK to re-route the MIDI events to another program that supports SFZ, like LinuxSampler.

**Comment by pachadotdev** [comment]
> Steinway B-211 makes use of specific SFZ-only opcodes that are not supported by the SF2 format.
> Converting it will cause these opcodes to be ignored and the resulting SoundFont will not sound as it's meant to do, and it might also have some issues on certain synthesizers (E.g. FluidSynth/QSynth).
> 
> I recommend using JACK to re-route the MIDI events to another program that supports SFZ, like LinuxSampler.

thanks a lot, I shall report how it works, I want to re-route my keyboard to use this amazing sound
